sudo: enabled
language: python
python:
  - "3.6"

before_install: docker-compose build

script: 
  - docker-compose up -d
  - sleep 10
  - docker-compose run crossweb coverage run --source=. manage.py test

after_success:
  - coveralls

